- name: MySQL Server
  apt: pkg=mysql-server state=present

- name: Install python-mysql
  apt: pkg=python-mysqldb state=present

- name: Update mysql root password for all root accounts so it doesn't have a blank password
  mysql_user: name=root host={{ item }} password={{ mysql_root_password }} login_user=root login_password={{ mysql_root_password }} check_implicit_admin=yes priv=*.*:ALL,GRANT
  with_items:
    - "{{ ansible_hostname }}"
    - 127.0.0.1
    - ::1
    - localhost

- name: Create database
  mysql_db: name={{ mysql_database }} state=present login_user={{ mysql_root_username }} login_password={{ mysql_root_password }}

- name: Create database user
  mysql_user: name={{ mysql_username }} password={{ mysql_password }} priv={{ mysql_database }}.*:ALL state=present host="%" login_user={{ mysql_root_username }} login_password={{ mysql_root_password }}

- name: Import SQL Structure
  mysql_db: name={{ mysql_database }} state=import target=/var/mybudget.io/sql/structure.sql login_user={{ mysql_root_username }} login_password={{ mysql_root_password }}