---

- name: Install nginx
  apt: pkg=nginx state=present

- name: Remove nginx default sites-enabled
  file: path=/etc/nginx/sites-enabled/default state=absent

- name: Install sites-enabled/mybudget.conf
  template: src=mybudget.conf.j2 dest=/etc/nginx/sites-enabled/mybudget.conf group=www-data owner=www-data mode=0644
  notify: restart nginx