---

- name: Vagrant - Install NGINX, Memcache, MySQL and PHP-FPM
  hosts: vagrant
  remote_user: root
  sudo: yes
  roles:
    - nginx
    - php-fpm
    - mysql
    - composer
    - memcache
    - beanstalk
    - geoip
    - mybudget